# Generated by Django 4.2.6 on 2023-10-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
